//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cześć.
        /// </summary>
        public static string testString {
            get {
                return ResourceManager.GetString("testString", resourceCulture);
            }
        }
		/// <summary>
		/// 	Looks up a localized string similar to Testowy ciąg
		/// </summary>
		public static string TestString {
			get {
				return ResourceManager.GetString("TestString", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to witam w śiwecie rozszerzeń
		/// </summary>
		public static string TransWorldWelcome {
			get {
				return ResourceManager.GetString("TransWorldWelcome", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to testowty ciąg
		/// </summary>
		public static string testString2 {
			get {
				return ResourceManager.GetString("testString2", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to testoey ciąg
		/// </summary>
		public static string testStr {
			get {
				return ResourceManager.GetString("testStr", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to cos cos ocs:
		/// </summary>
		public static string testString34 {
			get {
				return ResourceManager.GetString("testString34", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to asdfaefawefa
		/// </summary>
		public static string finallyAddedString {
			get {
				return ResourceManager.GetString("finallyAddedString", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to Hello World!
		/// </summary>
		public static string afawfe {
			get {
				return ResourceManager.GetString("afawfe", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to bla ciąg
		/// </summary>
		public static string blaString {
			get {
				return ResourceManager.GetString("blaString", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to jakiś losowwy cuą znaków
		/// </summary>
		public static string rndStringSome {
			get {
				return ResourceManager.GetString("rndStringSome", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to basdfaasdfa
		/// </summary>
		public static string blaString2 {
			get {
				return ResourceManager.GetString("blaString2", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to ggggggg
		/// </summary>
		public static string blaString344 {
			get {
				return ResourceManager.GetString("blaString344", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to Sdfgafrefa
		/// </summary>
		public static string blaString1345 {
			get {
				return ResourceManager.GetString("blaString1345", resourceCulture);
			}
		}
		/// <summary>
		/// 	Looks up a localized string similar to asfdasdfA
		/// </summary>
		public static string testString777 {
			get {
				return ResourceManager.GetString("testString777", resourceCulture);
			}
		}
	}
}
